version: '3.4' 

services:
  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 5050:80
    networks:
      - amigoscode 
      
  postgresql:
    image: postgres:latest
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
    - 5432:5432
    expose:
      - 5432:5432      
    networks:
      - default
      - amigoscode 

networks:
  amigoscode:
    driver: bridge   