version: '3.4' 

services:

  postgresql:
    image: postgres:latest
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: amigoscode
    ports:
      - 5432:5432
    expose:
      - 5432:5432
    networks:
      - amigoscode

  pgadmin:
    container_name: pgadmin4
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
      - TZ=America/Sao_Paulo
    ports:
      - 5050:80
    depends_on:
      - postgresql
    networks:
      - amigoscode 

  students:
    image: alanrmoreira/amigoscode:0.0.1-SNAPSHOT
    restart: always
    build:
      context: .
      dockerfile: SpringBoot/Dockerfile
    environment:
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgresql:5432/amigoscode
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: 1234
      SPRING.FLYWAY.URL: jdbc:postgresql://postgresql:5432/amigoscode
      SPRING.FLYWAY.USER: postgres
      SPRING.FLYWAY.PASSWORD: 1234
    ports:
      - 8000:8000
    depends_on:
      - postgresql
      -   pgadmin
    networks:
      - amigoscode

networks:
  amigoscode:
    driver: bridge   